str_display = string(str)+" Strength"
spd_display = string(spd)+" Speed"
mag_display = string(mag)+" Magic"
def_display = string(def)+" Defence"
res_display = string(res)+" Resistance"
luck_display = string(luck)+" Luck"